import type { Metadata } from "next";
import "./globals.css";
import { Source_Serif_4 } from 'next/font/google'
import { JetBrains_Mono } from 'next/font/google'

const serif = Source_Serif_4({ 
  subsets: ['latin'],
  variable: '--font-serif',
})
 
const mono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${serif.variable} ${mono.variable}`}>
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
